### ISSUE TITLE
End points for product 

### ISSUE THREAD

**Issue by gangadhar5613** [AltCampus/hack-1-request-for-product#9]
All functionality to create, update, delete, getting a product, along with the routes related to products.

/api/products/listing (POST)
/api/prodcuts/listing/edit (PUT)
/api/prodcuts/listing/edit (PUT)
 /api/products/listing/ (GET)
/api/products/:slug  (GET) (Getting a single product)

**Comment by sonu-kumar2001** [comment]
Completed following products route
creating product
getting single product
updating product
deleting a product
list of all the products
